version: '3'
services:
  app:
    build:
      context: ./
      args:
        BUILD_ENV: local
    volumes:
      - .:/var/www
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    ports:
      - "80:80"
    environment:
      - APP_ENV=local
