version: '3'
services:
    app:
        build:
            context: ./src
            dockerfile: ../Dockerfile
            args:
                BUILD_ENV: dev
        volumes:
            - ./src:/var/www/html
            - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
        ports:
            - "80:80"
        environment:
            - APP_ENV=local
