version: '3'
services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                BUILD_ENV: dev
        volumes:
            - ./src:/var/www/html
            - ./logs:/var/log/apache2
        ports:
            - "80:80"
        environment:
            - APP_ENV=local
